package shoppingList.domain;

public enum  ProductCategory {
    MEAT_AND_MEAT_PRODUCTS,
    FRUITS,
    VEGETABLES,
    SEASONING_GOODS,
    EDIBLE_FATS,
    MILK_PRODUCTS,
    GRAIN_AND_FLOUR_PRODUCTS,
    FISH_AND_FISH_PRODUCTS,
    EGGS_AND_EGG_PRODUCTS,
    NO_DATA,
}
